name: Publish Docker image for new releases

on:
  release:
    types:
      - published

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        id:   docker_build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          path: ./scripts/docker
          file: ./scripts/docker/Dockerfile.release
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/polkadot
          tags: latest
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
