name: Publish Docker image for new releases

on:
  release:
    types:
      - published

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: scripts/docker/Dockerfile.release
          tags: s3krit/polkadot:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
